# Generated by Django 5.0 on 2023-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('socialLink', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='education',
        ),
        migrations.RemoveField(
            model_name='team',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='team',
            name='social_link',
        ),
        migrations.AddField(
            model_name='team',
            name='education',
            field=models.ManyToManyField(related_name='team_education', to='education.education'),
        ),
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.ManyToManyField(related_name='team_experience', to='team.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='social_link',
            field=models.ManyToManyField(related_name='team_sociallink', to='socialLink.sociallink'),
        ),
    ]
