# Generated by Django 5.0 on 2023-12-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('education', '0001_initial'),
        ('socialLink', '0001_initial'),
        ('team', '0002_remove_team_education_remove_team_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_designation', to='designation.designation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='education',
            field=models.ManyToManyField(null=True, related_name='team_education', to='education.education'),
        ),
        migrations.AlterField(
            model_name='team',
            name='experience',
            field=models.ManyToManyField(null=True, related_name='team_experience', to='team.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='social_link',
            field=models.ManyToManyField(null=True, related_name='team_sociallink', to='socialLink.sociallink'),
        ),
    ]
