# Generated by Django 5.0 on 2023-12-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('team', '0003_alter_team_designation_alter_team_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.ManyToManyField(null=True, related_name='team_designation', to='designation.designation'),
        ),
    ]
