# Generated by Django 5.0 on 2023-12-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career'),
        ),
    ]
