# Generated by Django 5.0 on 2023-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/Tools')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image1/Tools')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image2/Tools')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image3/Tools')),
                ('tags', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('slug', models.CharField(max_length=100)),
                ('downloads', models.IntegerField(null=True)),
            ],
        ),
    ]
